---
document:
  name: "Protocollo d'intesa per la promozione e la verifica della trasformazione digitale della Pubblica Amministrazione"
  description: "Protocollo d'intesa per la promozione e la verifica della trasformazione digitale della Pubblica Amministrazione"
  tags:
    - "Corte dei Conti"
    - "Team Digitale"
    - "Protocollo d'intesa"
